name: Vault Integration

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest

    services:
      vault:
        image: vault:1.15.4
        ports:
          - 8200:8200
        options: >-
          --cap-add=IPC_LOCK
          -e 'VAULT_DEV_ROOT_TOKEN_ID=myroot'
          -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200'

    steps:
      # Логин в Docker Hub перед инициализацией контейнеров
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Установка Vault CLI
      - name: Install Vault CLI
        run: |
          sudo apt-get update && sudo apt-get install -y unzip curl
          curl -fsSL https://releases.hashicorp.com/vault/1.15.0/vault_1.15.0_linux_amd64.zip -o vault.zip
          unzip vault.zip && sudo mv vault /usr/local/bin/

      # Аутентификация и извлечение секрета
      - name: Authenticate and Fetch Secret
        env:
          VAULT_ADDR: "http://localhost:8200"
          VAULT_TOKEN: "myroot"
        run: |
          vault kv put secret/github-ci username="admin" password="securepassword"
          vault kv get -format=json secret/github-ci > secret.json

      # Проверка секрета
      - name: Verify Secret
        run: |
          cat secret.json
