name: Vault Integration

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    services:
      vault:
        image: vault:1.13.3
        options: >
          --cap-add=IPC_LOCK
          -e VAULT_DEV_ROOT_TOKEN_ID=myroot
          -e VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200

    steps:
      - name: Wait for Vault to be Ready
        run: |
          for i in {1..5}; do
            curl -fs http://vault:8200/v1/sys/health && break || sleep 5
          done
          echo "Vault is ready!"

      - name: Install Vault CLI
        run: |
          curl -fsSL https://releases.hashicorp.com/vault/1.15.0/vault_1.15.0_linux_amd64.zip -o vault.zip
          unzip vault.zip
          sudo mv vault /usr/local/bin/
          vault --version

      - name: Authenticate and Fetch Secret
        env:
          VAULT_ADDR: "http://vault:8200"
          VAULT_TOKEN: "myroot"
        run: |
          vault kv put secret/github-ci username=admin password=securepassword
          vault kv get -format=json secret/github-ci
