name: Vault Integration

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest

    services:
      vault:
        image: vault:1.12.8
        ports:
          - 8200:8200
        options: >
          --cap-add=IPC_LOCK
          -e VAULT_DEV_ROOT_TOKEN_ID=myroot
          -e VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200

    steps:
      - name: Wait for Vault to be Ready
        run: |
          for i in {1..20}; do
            curl -fs http://127.0.0.1:8200/v1/sys/health && break || sleep 5
          done
          echo "Vault is ready!"

      - name: Test Vault Status
        run: curl http://127.0.0.1:8200/v1/sys/health || echo "Vault is not running"

      - name: Verify Running Containers
        run: docker ps || echo "No running containers"

      - name: Verify Vault Container Logs
        run: |
          docker ps -a
          docker logs $(docker ps -q --filter "ancestor=vault:1.15.0") || echo "Vault logs are unavailable"

      - name: Check Container Status
        run: |
          docker ps -a
          docker inspect $(docker ps -aq --filter "ancestor=vault:1.15.0") || echo "Container inspect failed"

      - name: Install Vault CLI
        run: |
          sudo apt-get update && sudo apt-get install -y unzip curl
          curl -fsSL https://releases.hashicorp.com/vault/1.15.0/vault_1.15.0_linux_amd64.zip -o vault.zip
          unzip vault.zip && sudo mv vault /usr/local/bin/

      - name: Authenticate and Fetch Secret
        env:
          VAULT_ADDR: "http://127.0.0.1:8200"
          VAULT_TOKEN: "myroot"
        run: |
          vault kv put secret/github-ci username="admin" password="securepassword"

      - name: Verify Secret
        run: |
          vault kv get -format=json secret/github-ci > secret.json
          cat secret.json
