name: Retrieve Vault Secrets

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    permissions:
      contents: read
      id-token: write # Разрешение для OIDC токена

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Import Secrets from Vault
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.mycompany.com:8200
          method: jwt
          role: github-actions
          secrets: |
            secret/data/ci/aws accessKey | AWS_ACCESS_KEY_ID ;
            secret/data/ci/aws secretKey | AWS_SECRET_ACCESS_KEY ;

      - name: Use Imported Secrets
        run: |
          echo "Access Key ID: ${{ env.AWS_ACCESS_KEY_ID }}"
          echo "Secret Access Key: ${{ env.AWS_SECRET_ACCESS_KEY }}"
