name: Retrieve Vault Secrets

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    services:
      vault:
        image: hashicorp/vault:latest
        options: >
          --cap-add=IPC_LOCK
          -e VAULT_DEV_ROOT_TOKEN_ID=myroot
          -e VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Vault to be Ready
        run: |
          for i in {1..10}; do
            curl -fs http://vault:8200/v1/sys/health && break || sleep 5
          done
          echo "Vault is ready!"

      - name: Import Secrets from Vault
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault:8200
          method: token
          token: myroot
          secrets: |
            secret/data/ci/aws accessKey | AWS_ACCESS_KEY_ID ;
            secret/data/ci/aws secretKey | AWS_SECRET_ACCESS_KEY ;

      - name: Use Imported Secrets
        run: |
          echo "Access Key ID: ${{ env.AWS_ACCESS_KEY_ID }}"
          echo "Secret Access Key: ${{ env.AWS_SECRET_ACCESS_KEY }}"
